# Site settings
title: Business × Technology × Podcasts
subtitle: from Tunisia
email: hello@algora-labs.com
description: Podcast aggregator for technology fans and professionals
baseurl: ""
url: "https://techvibes.algora-labs.com"
copyright: '&copy; 2019-present AlgoraLabs. All rights reserved. '
logo: /assets/images/logo.png

# Build settings
markdown: kramdown
future: true

# https://getmdl.io/customize/index.html
material_theme: teal-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)
google-analytics-ua: UA-131380622-4

# Disqus shortname (not your username), without adding disqus.com at the end
disqus: algora-labs

# Format links
permalink: /podcasts/:title/
paginate_path: /podcasts/:num/

# Pagination
paginate: 9

# Use the following plugins
plugins_dir: ./_scripts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

