# Site settings
title: Tunisia × Tech × Podcasts
email: hello@algora-labs.com
description: Tunisia × Tech × Podcasts
baseurl: ""
url: "https://tunisiatech.algora-labs.com"
copyright: '&copy; 2019-present AlgoraLabs. All rights reserved. '

# Build settings
markdown: kramdown

# https://getmdl.io/customize/index.html
material_theme: red-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)
#google-analytics-ua: UA-84475574-1
